#!/bin/bash

usage() { 
echo
echo -e "--------------------------------------------------------------------------"
echo -e "\e[1mmangupa is simple tools for searching web shell script and defaced result\e[0m"
echo -e "--------------------------------------------------------------------------"
echo -e "\e[240mUsage \t:\e[0m\n \e[1m\e[240m $0 /path/\e[0m"
echo -e "\e[240mExample :\n \e[1m\e[240m $0 /var/www/html/\e[0m"  
echo
1>&2; exit 1; 
		}
#input path		
path="$@"

#handle if path not input
if [ -z "${path}" ]; then
	usage
fi

#File output
FILE1='output/output1.txt'
FILE2="output/$(date '+%d-%B-%Y').txt"


# check file and remove
if test -f "$FILE1"; then
	rm "$FILE1"
fi

if test -f "$FILE2"; then
	rm "$FILE2"
fi
echo
echo -en "\e[1m \e[32mPlease Wait....\e[0m\t"

#sleep 1 second
sleep 2

for i in $(cat list.txt); do
	grep -rwioa $i ${path} >> output/output1.txt
done

#sort duplicate folder
sort -u output/output1.txt >> output/$(date '+%d-%B-%Y').txt

echo
echo -e "\e[1m \e[32mSUCCESSFULLY COMPLETED\e[0m"
echo
echo -e "\e[1m \e[41m[✔] $(sort -u output/$(date '+%d-%B-%Y').txt | wc -l) FILE DETECTED\e[0m"
sleep 1
echo

#Show output
for i in $(cat output/$(date '+%d-%B-%Y').txt | head -n24); do
	echo -e "\e[1m[+] $i\e[0m"
done
echo
echo -e "\e[1m \e[42mPlease check folder output/$(date '+%d-%B-%Y').txt\e[0m"
echo
#remove output1.txt
rm "$FILE1"